### ISSUE TITLE
Charts in Hybrid app don't seem to work

### ISSUE THREAD

**Issue by TaraCampagne** [mendixlabs/charts#19]
Hi,

Thanks for the fixes in the last release!
I have some additional things I've noticed:
- The charts don't seem to work on the hybrid app? Nothing is shown while in the webbrowser on the phone the charts look really neat.
- On the phone webbrowser the rangeslider is shown but we are not able to use it.
- I don't seem to be able to costomize the widget in a way the range slider is excluded, it would be really nice if it possible to choose when to use it and when to hide it.

Cheers!
Tara

**Comment by edwinmp** [comment]
Hi @TaraCampagne ... Thanks for the feedback.
However, I have failed to replicate your issue on Hybrid (It is one of the issues that were fixed in the new release). On which platform (Android/IOS) is it occurring, and on what OS version?

Also, the range slider can be shown or hidden based on a the widget property "Show range slider" in the Chart properties tab (only for the time series, which is the only widget that supports it explicitly).

You are right about touch events not being functional for the range slider on mobile. It's a known [issue](https://github.com/plotly/plotly.js/issues/1098) on Plotly. Will see if there's a way to fix it ourselves. In the mean time, it may only be good for zooming in but you can do that on the chart itself.

Regards,
Edwin

**Comment by Andries-Smit** [comment]
Issue is closed due to no response, please open a new issue with Mendix support when it is relevant
