### ISSUE TITLE
Custom settings for marker don't work

### ISSUE THREAD

**Issue by madnessxd** [mendixlabs/charts#2]
I'm working on an app and want to change the color of the markers.
I'm debugging it at this website and it works the same way as in mendix itself:
https://charts102.mxapps.io/

The legend is editable, but none of these work for me:

```
{
    "marker": {
        "colors" : ["#FF00FF", "#FFFF00", "#00FFFF"],
        "line": {
            "color": "#FF00FF",
            "width": 10
        }
    }
}
```

More info about my syntax here:
https://plot.ly/javascript/reference/#pie-marker

**Comment by edwinmp** [comment]
Hi @madnessxd ... sorry for the delayed response.
For the pie chart, there are two sets of configurations you can edit: the layout options & the data options. Perhaps "data" is not the most accurate naming for this.
In short, the marker property above is to be set under the data option since its configs affect a singular pie, and Plotly supports the addition of several.

![charts](https://user-images.githubusercontent.com/5672438/33663310-78f336bc-daa0-11e7-8bb2-e82e56fcc525.gif)

**Comment by madnessxd** [comment]
@edwinmp Where did the config menu go to? I can't seem to find the Toggle Editor button that is visible in your animated gif.
I tried Firefox, Chrome, IE, Edge.

**Comment by edwinmp** [comment]
Thanks @madnessxd ... that's an urgent issue. Let me get right on it.

**Comment by edwinmp** [comment]
@madnessxd Fixed the demo project. FYI, planning to release a new version of the widget this week, including the Area & Bar charts...

**Comment by madnessxd** [comment]
@edwinmp Everything works perfect now :)
