### ISSUE TITLE
Set Enum values for Name attribute instead of just string.

### ISSUE THREAD

**Issue by Jflax** [mendixlabs/charts#68]
I would like to be able to use a enum value to set the name attribute instead of only string. 
The workaround seems elongated to create a microflow to getCaption instead of being able to directly configure in the widget.

**Comment by djkwagala** [comment]
Hi @Jflax,
Thanks for the feedback. We'll discuss with the product owner about this feature request.

Regards
Derrick

**Comment by Andries-Smit** [comment]
Dear Flax

For dynamic series, it is already possible to select a string or a enum attribute. 
https://github.com/mendixlabs/charts/blob/master/src/LineChart/LineChart.xml#L152-L160

Could you please explain in more details what your problem is? 
Does it show the enum `name `instead of the enum `Caption`?

Kind regards, Andries

**Comment by Andries-Smit** [comment]
Implemented, available in App store release v1.4.2 https://appstore.home.mendix.com/link/app/105695/
